name: Delete multiple branches
description: Delete multiple branches from repository
author: dawidd6
branding:
  icon: git-branch
  color: red
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  branches:
    description: Branches to delete (comma separated)
    required: false
  numbers:
    description: PR numbers whose head branches should be deleted (comma separated)
    required: false
  prefix:
    description: Additional prefix to append to every branch name
    required: false
  suffix:
    description: Additional suffix to append to every branch name
    required: false
  dry_run:
    description: Runs the action without deleting branhes
    required: false
  days:
    description: Delete branches that are older than the today's date minus number of days
    required: false
runs:
  using: node12
  main: main.js
