name: Suffix Test action

on:
  push:
    branches:
      - "**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create branches
        run: |
          git checkout -b test1-suffix
          git push -f origin test1-suffix
          git checkout -b test2-suffix
          git push -f origin test2-suffix
      - name: Test action
        uses: ./
        with:
          branches: test1,test2
          suffix: -suffix
